Move around local declaration

diff --git a/snap b/snap
--- a/snap
+++ b/snap
@@ -1,10 +1,10 @@
 #!/bin/bash
 
 status_text() {
-    if test "$ok" -eq "0"; then
-	echo "SUCCESS ($ok)"
+    if test "$1" -eq "0"; then
+	echo "SUCCESS ($1)"
     else
-	echo "FAILURE ($ok)"
+	echo "FAILURE ($1)"
     fi
 }
 
@@ -49,14 +49,9 @@ EOF
 }
 
 _actual_backup() {
-    local src
-    local dst
-    local ok
-    local begin_time
-    local end_time
-    src="$1"
+    local src="$1"
     shift
-    dst="$1"
+    local dst="$1"
     shift
     case "$src" in 
 	(*/) ;;
@@ -71,7 +66,7 @@ _actual_backup() {
 	    ;;
     esac
 
-    begin_time="$(date --rfc-3339=seconds)"
+    local begin_time="$(date --rfc-3339=seconds)"
 	
     echo "--- BEGIN $begin_time $src to $dst"
     RSYNC_RSH="$RSYNC_RSH" \
@@ -83,19 +78,19 @@ _actual_backup() {
 	  --filter ":- .exclude_backup" \
 	  "$@" \
 	  "$src" "$dst"
-    ok=$?
-    end_time="$(date --rfc-3339=seconds)"
+    local ok=$?
+    local end_time="$(date --rfc-3339=seconds)"
     echo "--- END $end_time $src to $dst, Status: $ok"
     return $ok
 }
 
 live_backup_dir() {
-    orig_dir="$1"
-    name="$(echo "$orig_dir" | tr '/' '_')"
-    src_dir="${remote_host:+$remote_host:}$orig_dir"
-    target_dir="$current_backup_dir/$name/"
+    local orig_dir="$1"
+    local name="$(echo "$orig_dir" | tr '/' '_')"
+    local src_dir="${remote_host:+$remote_host:}$orig_dir"
+    local target_dir="$current_backup_dir/$name/"
     _actual_backup "$src_dir" "$target_dir"
-    ok="$?"
+    local ok="$?"
     # $?==3 means "stuff changed", OK that
     test "$ok" -eq "3" && ok="0"
     # $?==24 means "files vanished before transferred", OK THAT
@@ -104,6 +99,7 @@ live_backup_dir() {
 }
 
 live_backup_dirs() {
+  local ok
   for d in "$@"; do
       live_backup_dir "$d"
       ok=$?
@@ -146,31 +142,29 @@ either_backup_dirs_or_snap() {
 }
 
 make_backup_() {
-  local begin_time
-  local end_time
-  local ok
-
-  begin_time="$(date --rfc-3339=seconds)"
+  local begin_time="$(date --rfc-3339=seconds)"
   echo "--- BACKUP START $@: $begin_time, Timestamp: $NOW"
   cleanup \
       && either_backup_dirs_or_snap \
       && current_snap
-  ok=$?
-  end_time="$(date --rfc-3339=seconds)"
+  local ok=$?
+  local end_time="$(date --rfc-3339=seconds)"
   echo "--- BACKUP END $@: $end_time, Status: $ok"
   return $ok
 }
 make_backup() {
-  local begin_time
-  local end_time
-  local ok
-  begin_time="$(date --rfc-3339=seconds)"
+  local begin_time="$(date --rfc-3339=seconds)"
   read_config "$1" \
       && make_backup_ "$@" >"$backup_log" 2> >(tee "$backup_log.err" >&2)
-  ok=$?
-  end_time="$(date --rfc-3339=seconds)"
-  ok_text="$(status_text $ok)"
-  echo "$ok_text; @${backup_host}; ${backup_dirs}; END:$end_time BEGIN:$begin_time" 1>&2
+  local ok=$?
+  local end_time="$(date --rfc-3339=seconds)"
+  local ok_text="$(status_text $ok)"
+  local msg="$ok_text; @${backup_host}; ${backup_dirs}; END:$end_time BEGIN:$begin_time" 1>&2
+  if test "$ok" -eq "0"; then
+      echo "$msg"
+  else
+      echo "$msg" 1>&2
+  fi
   return $ok
 }
 
@@ -184,13 +178,21 @@ cleanup() {
 }
 
 backup_hosts() {
-  all_ok="0"
+  local failures=0
+  local count=0
   for x in "$@"; do 
     make_backup "$x"
     ok=$?
-    test '!' "$ok" -eq "0" && all_ok="$ok"
-    echo "* ok=$ok, all_ok=$all_ok"
+    count=$((count + 1))
+    test '!' "$ok" -eq "0" && failures=$((failures + 1))
   done
+  local msg="$failures failures of $count backups"
+  if test '!' "$failures" -eq "0"; then
+    echo "*****************************" 1>&2
+    echo "$msg" 1>&2
+  else
+    echo "$msg"
+  fi
   return $all_ok
 }
 
